GET http://localhost:8080/spring-mvc-app/api/v1/user/all
Authorization: Basic admin 123

###

GET  http://localhost:8080/spring-mvc-app/api/v1/user/filter?page=1&size=3&usernameFilter=&minAge=&maxAge=&sortField=

###

GET http://localhost:8080/spring-mvc-app/api/v1/user/3

###

POST http://localhost:8080/spring-mvc-app/api/v1/user
Content-Type: application/json
Authorization: Basic guest 123

{
    "username": "from rest",
    "age": 43,
    "password": "ppp"
}

###

PUT http://localhost:8080/spring-mvc-app/api/v1/user
Content-Type: application/json

{
    "id": 6,
    "username": "from rest",
    "age": 45
}

###

DELETE http://localhost:8080/spring-mvc-app/api/v1/user/6
